RedPicFront:: 	INCBIN "gfx/player/red.pic"
GreenPicFront:: INCBIN "gfx/player/green.pic"
YellowPicFront:: INCBIN "gfx/player/yellow.pic"
PinkPicFront:: INCBIN "gfx/player/pink.pic"
ShrinkPic1::  	INCBIN "gfx/player/shrink1.pic"
ShrinkPic2::  	INCBIN "gfx/player/shrink2.pic"
